load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

COMMON_TEST_SRCS = glob(["tests/common/**/*.rs"])

rust_library(
    name = "opensovd_client",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(normal = True, proc_macro = True),
    crate_name = "opensovd_client",
    compile_data = ["README.md"],
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True) + [
        "//opensovd-models:opensovd_models",
    ],
)

rust_test(
    name = "unit_test",
    crate = ":opensovd_client",
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)

rust_test(
    name = "apps_test",
    srcs = ["tests/apps.rs"] + COMMON_TEST_SRCS,
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_root = "tests/apps.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True, normal_dev = True) + [":opensovd_client"],
)

rust_test(
    name = "areas_test",
    srcs = ["tests/areas.rs"] + COMMON_TEST_SRCS,
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_root = "tests/areas.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True, normal_dev = True) + [":opensovd_client"],
)

rust_test(
    name = "client_test",
    srcs = ["tests/client.rs"] + COMMON_TEST_SRCS,
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_root = "tests/client.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True, normal_dev = True) + [":opensovd_client"],
)

rust_test(
    name = "components_test",
    srcs = ["tests/components.rs"] + COMMON_TEST_SRCS,
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_root = "tests/components.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True, normal_dev = True) + [":opensovd_client"],
)

rust_test(
    name = "data_test",
    srcs = ["tests/data.rs"] + COMMON_TEST_SRCS,
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_root = "tests/data.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True, normal_dev = True) + [":opensovd_client"],
)

rust_test(
    name = "unix_test",
    srcs = ["tests/unix.rs"] + COMMON_TEST_SRCS,
    aliases = aliases(
        normal = True,
        normal_dev = True,
        proc_macro = True,
        proc_macro_dev = True,
    ),
    crate_root = "tests/unix.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True, proc_macro_dev = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True, normal_dev = True) + [":opensovd_client"],
)
