# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

exports_files([
    "Cargo.lock",
    "Cargo.toml",
    "rust-toolchain.toml",
])

package_group(
    name = "workspace_crates",
    packages = ["//..."],
)

alias(
    name = "opensovd-gateway",
    actual = "//opensovd-cli/gateway:opensovd_gateway",
)
