# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

unstable_features = true
newline_style = "Unix"
group_imports = "StdExternalCrate"
style_edition = "2024"
max_width = 100
