load("//bazel:rust_crate.bzl", "workspace_rust_library", "workspace_rust_test")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

workspace_rust_library(
    name = "opensovd_models",
    srcs = glob(["src/**/*.rs"]),
    crate_deps = [
        "schemars",
        "serde",
        "serde_json",
    ],
    crate_features = ["jsonschema"],
    crate_name = "opensovd_models",
    crate_root = "src/lib.rs",
    version = "0.1.1",
)

workspace_rust_test(
    name = "unit_test",
    crate = ":opensovd_models",
)
