load("@crate_index//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

exports_files(["Cargo.toml"])

cargo_build_script(
    name = "build_script_build",
    srcs = ["build.rs"],
    aliases = aliases(build = True, build_proc_macro = True),
    crate_name = "build_script_build",
    crate_root = "build.rs",
    edition = "2024",
    pkg_name = "opensovd-gateway",
    version = "0.1.1",
    deps = all_crate_deps(build = True),
    proc_macro_deps = all_crate_deps(build_proc_macro = True),
)

rust_binary(
    name = "opensovd_gateway",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(normal = True, proc_macro = True),
    crate_features = ["default"],
    crate_name = "opensovd_gateway",
    crate_root = "src/main.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    version = "0.1.1",
    deps = all_crate_deps(normal = True) + [
        ":build_script_build",
        "//opensovd-cli/lib:libcli",
        "//opensovd-core:opensovd_core",
        "//opensovd-extra:opensovd_extra",
        "//opensovd-mocks:opensovd_mocks",
        "//opensovd-server:opensovd_server",
    ],
)
