# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

FROM gcr.io/distroless/cc-debian13:nonroot
ARG TARGETARCH

COPY dist/${TARGETARCH}/opensovd-gateway /usr/local/bin/opensovd-gateway

EXPOSE 7690

ENV SOVD_URL=http://0.0.0.0:7690/sovd
ENTRYPOINT ["/usr/local/bin/opensovd-gateway"]
