# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "opensovd-examples-server"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[example]]
name = "simple"
path = "simple/simple.rs"

[[example]]
name = "systemd"
path = "systemd/systemd.rs"

[[example]]
name = "auth"
path = "auth/auth.rs"


[[example]]
name = "mtls"
path = "mtls/mtls.rs"
required-features = ["tls"]

[[example]]
name = "hpc-sovd-server"
path = "hpc-sovd-server/hpc-sovd-server.rs"

[features]
tls = ["opensovd-server/tls"]

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = ["json", "tokio", "http1"] }
jsonwebtoken = { workspace = true }
libcli = { workspace = true }
opensovd-core = { workspace = true }
opensovd-extra = { workspace = true, features = ["auth"] }
opensovd-mocks = { workspace = true }
opensovd-models = { workspace = true }
opensovd-providers = { workspace = true }
opensovd-server = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
sysinfo = { workspace = true, features = ["component", "disk"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "macros", "fs"] }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
sd-notify = { workspace = true }

[lints]
workspace = true
