# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

load("@crate_index//:crates.bzl", "aliases", "all_crate_deps")
load("@rules_rust//cargo:defs.bzl", "cargo_toml_env_vars")
load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

cargo_toml_env_vars(
    name = "cargo_env",
    src = "Cargo.toml",
    workspace = "//:Cargo.toml",
)

rust_library(
    name = "opensovd-core",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(
        normal = True,
        proc_macro = True,
    ),
    crate_name = "opensovd_core",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_env"],
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)
