#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
#
# Point Bazel at the cache volume mounted by devcontainer.json.

set -euo pipefail

CACHE_DIR=/var/cache/bazel

{
  echo "# Generated by .devcontainer/configure-bazel.sh. Edits will be overwritten."
  if [ -d "$CACHE_DIR" ]; then
    if [ "$(stat -c '%U:%G' "$CACHE_DIR")" != "$(id -un):$(id -gn)" ]; then
      sudo chown -R "$(id -un):$(id -gn)" "$CACHE_DIR"
    fi
    echo "startup --output_user_root=${CACHE_DIR}"
    echo "common --disk_cache=${CACHE_DIR}/diskcache"
  else
    echo "common --disk_cache=${HOME}/.cache/bazel/_disk_cache"
  fi
  echo "common --experimental_disk_cache_gc_max_age=60d"
  echo "common --experimental_disk_cache_gc_max_size=50G"
} > "$HOME/.bazelrc"
