# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "opensovd-examples-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[example]]
name = "client"
path = "src/client.rs"

[dependencies]
bytes = { workspace = true }
clap = { workspace = true, features = ["derive", "help", "std", "usage"] }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1"] }
libcli = { workspace = true }
opensovd-client = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["net", "rt", "macros", "signal"] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }

[lints]
workspace = true
