# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "opensovd-examples-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[example]]
name = "client"
path = "src/client.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "help", "std", "usage"] }
libcli = { workspace = true }
opensovd-client = { workspace = true }
opensovd-extra = { workspace = true, features = ["trace"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["net", "rt", "macros", "signal"] }

[lints]
workspace = true
