# SPDX-FileCopyrightText: 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "sovd-handlers"
version = "0.1.0"
edition.workspace = true
publish = false
description = "SOVD handlers"
homepage.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]

# internal dependencies
openapi_client = { workspace = true }

async-trait       = { workspace = true }
chrono            = { workspace = true }
futures           = { workspace = true }
swagger           = { workspace = true }
log               = { workspace = true }
flexi_logger      = { workspace = true }
mime              = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
hyper             = { workspace = true }
serde_ignored     = { workspace = true }
url               = { workspace = true }
lazy_static       = { workspace = true }
percent-encoding  = { workspace = true }
regex             = { workspace = true }
frunk_derives     = { workspace = true }
frunk_core        = { workspace = true }
frunk-enum-derive = { workspace = true }
frunk-enum-core   = { workspace = true }
clap              = { workspace = true }
env_logger        = { workspace = true }
tokio             = { workspace = true }
tokio-openssl     = { workspace = true }
libc              = { workspace = true }
procfs            = { workspace = true }
once_cell         = { workspace = true }
sysinfo           = { workspace = true }
openssl           = { workspace = true }
mdns-sd           = { workspace = true }
multer            = { workspace = true }
bytes             = { workspace = true }
anyhow            = { workspace = true }
